# Generated by Django 4.2.13 on 2024-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=0, upload_to='media/'),
            preserve_default=False,
        ),
    ]
